language: node_js
node_js:
- '4.1'
script:
- npm run ci
deploy:
  provider: openshift
  user: mbr.robertson@gmail.com
  password:
    secure: L5k5F+9j25pQMmLvZqivNKtgdTUl2ovyygxtdwK3n4TCfSvYVU5zjMdcOfXxogtujJU+Uqpdv2Hg9wC5ZDUs6LZGHjqhoB3hbP4AajzjVPgL8hk4GDsUdbUQ7VECOJ9oQNRVpBA/U+xk62Z/Cb7L11yXS+CNpWFi+DbnLeSUk3vN628a0I0wKT0Vdo1yjU4Aaeb7cP4ev2j1CiNxyDL4UHQXpUjI9DHBiqBWpM60GQD82DAiA+He3qUBIyghn/1ix5sJQBYxRFYInvMII+4O4tEZtKTdfM1lJn2hzL4Dl0I+rC/ZNPZLRi9FE8TomAfFUEcAn0wOjZN4+gHdVJB+rKk3ezkX0esVEUmV0M7sfsfnCTmSNomYiAkYmPgBGgGCHXttVZCFf+4LLcrxPt6Aoh07y/BALpDzpgKi/p+fnipAT/caDtk9UCGFfifXuppU9wNBSt8u5lBQn2dHJcQ3U9wjDzf8VWi+Gvc3gJHZl5x/j1LCYf9MPhjEP/Oa0I6IJC0fmCna+/reXDF0MNswiIklL94DQTnrKDzlK6B/SOJG4sYZ/dEKY3PQgKyi28CjOFzshmy8+l40toLjoVjRGzf/HREupAPxi/PgrMGts/2ac73oOOBnjp/nm3DXxr8mjwQIV0hUcAxJBEwTAnWlAb/10iiklG26JegmyXv9Auc=
  app: chspe
  domain: mbrobertson
  on:
    repo: TheImpersonator/CHSPE
